/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrediccionesRouteImport } from './routes/predicciones'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as GraficosRouteImport } from './routes/graficos'
import { Route as IndexRouteImport } from './routes/index'

const PrediccionesRoute = PrediccionesRouteImport.update({
  id: '/predicciones',
  path: '/predicciones',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const GraficosRoute = GraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graficos': typeof GraficosRoute
  '/historial': typeof HistorialRoute
  '/predicciones': typeof PrediccionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graficos': typeof GraficosRoute
  '/historial': typeof HistorialRoute
  '/predicciones': typeof PrediccionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graficos': typeof GraficosRoute
  '/historial': typeof HistorialRoute
  '/predicciones': typeof PrediccionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/graficos' | '/historial' | '/predicciones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graficos' | '/historial' | '/predicciones'
  id: '__root__' | '/' | '/graficos' | '/historial' | '/predicciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraficosRoute: typeof GraficosRoute
  HistorialRoute: typeof HistorialRoute
  PrediccionesRoute: typeof PrediccionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predicciones': {
      id: '/predicciones'
      path: '/predicciones'
      fullPath: '/predicciones'
      preLoaderRoute: typeof PrediccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graficos': {
      id: '/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof GraficosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraficosRoute: GraficosRoute,
  HistorialRoute: HistorialRoute,
  PrediccionesRoute: PrediccionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
